### ISSUE TITLE
Page Title includes breadcrumb HTML 

### ISSUE THREAD

**Issue by Stephen-Gates** [theodi/ODMAT#171] opened 2015-04-13 22:19 UTC
![image](https://cloud.githubusercontent.com/assets/9379524/7126711/e91bef8c-e27e-11e4-8209-22efe96ca8e2.jpg)

**Comment by ldodds** [comment] 2015-04-14 13:50
Closing as duplicate of #157. Thanks for reporting this, and the others though!

**Closed by ldodds** 2015-04-14 13:50 UTC

**Comment by Stephen-Gates** [comment] 2015-04-14 13:52
No probs. I'll keep looking as we work our way through the questions.

**Comment by ldodds** [comment] 2015-04-14 13:55
Really appreciate the testing you're doing. Ping me if you want to to discuss anything that does fit here :)
